### ISSUE TITLE
Page not opening on my iPhone

### ISSUE THREAD

**Issue by saswimmer** [TheDabblingDuck/ankimote#22]
I have an iPhone and Mac and I tried to connect thru same wifi and bluetooth but I could not figure it out. When you say "Then find your phone's IP address on the Bluetooth connection, and use that IP address instead of the one Ankimote displays." I am not sure how to do that on an iPhone/Mac. Any suggestions on how I can use this on my devices?

**Comment by TheDabblingDuck** [comment]
As far as not being able to connect on the same wifi, try these things to fix them:

* Make sure VPN is off
* Make sure Anki has access through firewall (often the problem)
* Use your own wifi router (rather than one provided by your apartment, or a school network, because these sometimes stop devices from communicating with each other)

The bluetooth (can be done with Wifi too) thing involves creating a hotspot with your phone and connecting your laptop to it, so that they are on the same network. But I think iphone blocks communication with tethered devices - I've only ever got it to work on Android.
