### ISSUE TITLE
Ankimote swipes suddenly show/good becomes show/hard

### ISSUE THREAD

**Issue by homeslice2** [TheDabblingDuck/ankimote#28]
This issue was previously mentioned by someone but it is still occurring on my ankimote part of the time.  My button is set to show/good but sometimes it acts as show/hard. I updated my anki and have redownloaded the addon with no fix.  It will work perfectly for 30 minutes and then suddenly change.  Any help would be appreciated

**Comment by homeslice2** [comment]
Edit: Found out doesn't have to do with timing, just that learning cards specifically have this issue but no issues with reviews

**Comment by TheDabblingDuck** [comment]
This is interesting because the previous issue you mentioned most likely happened when using an older version of Anki with the V1 scheduler. I pushed an update that fixed the issue for that person.

I can't seem to replicate this issue on my Anki, so I'll need your help to figure out what's going on. Can you find and share the following?

1. Anki version
2. Operating system (windows/mac/linux?)
3. What scheduler version you are using - look at Anki preferences -> scheduling and see if you see any checked or unchecked boxes about the V1/V2/V3 scheduler.
4. Do you have any other addons that might be modifying scheduling related tasks, or modifying the answer buttons? If so, can you disable those addons and retry to see if that fixes it?
5. Open up a set of learning cards that you are having this problem with.  How many answer buttons show up - is it Again/Hard/Good/Easy, or Again/Good/Easy, or Again/Good, or something else?
6. Open up a set of learning cards that you are having this problem with. Go to the answer side of the card so you see the answer buttons. Then open up the Anki debug console by hitting `Ctrl+Shift+;` on Windows or `Command+Shift+;` on Mac. In the top box, paste in `print(mw.col.sched.answerButtons(mw.reviewer.card))` and then hit `Ctrl+Enter` on Windows or `Command+Enter` on Mac, and you should see that command output a number in the bottom box. What is that number?
7. In the debug console, can you clear out the top box and then paste in `pp(mw.col.sched_ver())`and run that? What scheduler version does it show you?

Thanks for the bug report!

**Comment by TheDabblingDuck** [comment]
This is the code responsible for answering cards:

```
                # handle answer
                bcount = mw.col.sched.answerButtons(mw.reviewer.card)
                if bcount<3:
                    # v1 scheduler and learning or relearning
                    if msg=='again':
                        mw.reviewer._answerCard(1)
                    elif msg=='good':
                        mw.reviewer._answerCard(2)
                elif bcount<4:
                    # v1 scheduler and learning or relearning
                    if msg=='again':
                        mw.reviewer._answerCard(1)
                    elif msg=='good':
                        mw.reviewer._answerCard(2)
                    elif msg=='easy':
                        mw.reviewer._answerCard(3)
                else:
                    # v2 scheduler (always 4 buttons) or V1 scheduler nonlearning
                    if msg=='again':
                        mw.reviewer._answerCard(1)
                    elif msg=='hard':
                        mw.reviewer._answerCard(2)
                    elif msg=='good':
                        mw.reviewer._answerCard(3)
                    elif msg=='easy':
                        mw.reviewer._answerCard(4)
```

If an intended 'good' is actually registering as 'hard', I'd guess you have a 3-button layout with Again/Hard/Good, and that my code doing `mw.reviewer._answerCard(2)` is the problem, as in your configuration, 2 means 'hard'. 

To fix this problem, I'd need to know when exactly this button configuration happens. Is it with re-learning cards (reviews you've gotten wrong the last time you answered)?

**Comment by TheDabblingDuck** [comment]
I think I have an idea of why this might be happening - if you're using the V1 scheduler, the card may be getting answered as you requested, but the feedback component is misinterpreting the ease.

Can you test the fix? Open the anki addons page, click ankimote, then 'view addon files', and in the folder that pops up, replace `__init__.py` with the version linked here:  https://gofile.io/d/td2t5q

**Comment by homeslice2** [comment]
I ended up just upgrading from V1 scheduler and it completely resolved the isse.  Thank you for the quick response
