### ISSUE TITLE
QR code leads me to a site that can't be reached.

### ISSUE THREAD

**Issue by rembrandtharmenszoonvanrijn** [TheDabblingDuck/ankimote#35]
Hey there, the title pretty much sums it up.

I added the add-on on my laptop (a Chromebook) and, after scanning the QR code with my android Xiaomi phone, I was led to a web page saying that [insert number] took too long to respond, and that the site can't be reached. 
The error: ERR_CONNECTION_TIMED_OUT

Any help would brilliant, though I understand that sometimes this add-on just may not work based on the circumstances.

Thanks!

**Comment by TheDabblingDuck** [comment]
Since you're on a Chromebook, I'm assuming you've installed Anki as a linux app. Linux apps run in a container that doesn't have access the internet ports needed for Ankimote by default.

1. Follow [this guide](https://chromeos.dev/en/web-environment/port-forwarding) to enable port forwarding for ports 61337 and 61338. Note that those switches can turn off when you restart your chromebook / the linux container, so you'll have to turn them back on sometimes. This step tells your chomebook to forward incoming connections on ports 61337 and 61338 to the linux container, where Anki is running.
2. Next, the QR code displayed by ankimote points to an IP address that is valid inside the linux container. However, you'll want to point your phone to the IP address of your chromebook itself, so that your phone knows where to look. Follow [these steps](https://support.google.com/chromebook/answer/1047420?hl=en#:~:text=You%27ll%20see%20your%20Chromebook%27s%20IP%20address) to find your chromebook's local IP address.
3. Lastly, on your android phone, open a browser and type in `http://[chromebook's local IP]:61337`. If what you got from step 2 was `192.168.0.123`, you'll want to point your phone's browser to `http://192.168.0.123:61337`. You'l have to do this every time - the QR code scanning won't work.

**Comment by rembrandtharmenszoonvanrijn** [comment]
Thanks so much!
