### ISSUE TITLE
Conflict with addons that modify answer buttons

### ISSUE THREAD

**Issue by keithcdodd** [TheDabblingDuck/ankimote#9]
Hello, this was working great till I updated to 2.1.35. The tap or swipe can reveal the card, but not mark it as good/show. I did not change any addons before updating. If I had to guess, it is probably conflicting with the addon Auto Ease Factor (which I do not want to get rid of) because it does make the buttons Pass/Fail. However, this was working fine/perfectly even with Auto Ease Factor before my update from 2.1.26 to 2.1.35. I do not have any other addon that I know of that changes the buttons at all...

Thanks!

**Comment by keithcdodd** [comment]
I was able to get it to work by turning off the "Pass Fail" option in the config for the addon Auto Ease Factor. Still curious that it only stopped working after updating to 2.1.35.  Not a deal breaker for sure. This is a wonderful addon. Thank you! 

Would maybe be cool if there could be audio feedback too (the visual feedback is wonderful already).

**Comment by TheDabblingDuck** [comment]
Hi Keith, thanks for the comment. Many users have had problems with addons that modify the buttons. I’ll look into this when I have time and push an update that bypasses the answer buttons. It might be a few months though as I am currently short for time.

**Comment by rumDMC** [comment]
I have auto ease factor but with the "Pass Fail" option turned off and it is not letting me rate a card. I can do everything else (scroll, reveal, amboss) but it wont receive any card rating regardless of swipe/tap mode. However, I also have "Advance Review Bottom Bar", which let me change the colors, so that's most likely what's causing the issue. Just wanted to relay that conflict, didn't feel like it deserved its own issue on github though. Love the addon!

**Comment by TheDabblingDuck** [comment]
Thanks for letting me know. I'll try to make it compatible with both pass/fail mode and the advance review bottom bar in the next update.

**Comment by gpshearn** [comment]
Just curious if you had any time or luck making this add-on compatible with Auto Ease Factor with pass/fail mode enabled? Thanks for your time! :)

**Comment by TheDabblingDuck** [comment]
Yes - the fix is pretty easy and I'll push an update once I fix a few other things as well (like the feedback not showing and scrolling issues on recent anki versions).

For now, if you want to fix it, go to the anki addons page, click Ankimote, click 'view addon files' and open up `__init__.py`

Find these lines:
```
if msg==label.lower():
    mw.reviewer._answerCard(ease)
```

And replace it with this instead:
```
if msg=='again':
    mw.reviewer._answerCard(1)
elif msg=='hard':
    mw.reviewer._answerCard(2)
elif msg=='good':
    mw.reviewer._answerCard(3)
elif msg=='easy':
    mw.reviewer._answerCard(4)
```

**Comment by TheDabblingDuck** [comment]
Alternatively replace that file with the version here. It also fixes scrolling and feedback. 

https://gofile.io/d/SPHhzl

**Comment by gpshearn** [comment]
Amazing! Thank you so much :)

**Comment by TheDabblingDuck** [comment]
Fixed in the latest version on ankiweb.
